# Override besu image with prefetch branch (commit f5bfe89)
besu_container_image: ethpandaops/besu:bal-devnet-2

besu_container_command_extra_args:
  - --genesis-file=/network-config/besu.json
  - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TXPOOL,WEB3
  - --sync-mode=FULL
  - --data-storage-format=BONSAI
  - --bonsai-limit-trie-logs-enabled=false
  - --bonsai-historical-block-limit=100000000
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --target-gas-limit=80000000
  - --Xbal-prefetch-reading-enabled=true
  - --Xbal-trust-state-root=true
  - --Xbal-perfect-parallelization-enabled=true
