# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/syncoor-web.yaml.j2

syncoor-web:
  fullnameOverride: syncoor-web
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.ethquokkaops.io/gh/ethpandaops/syncoor-web
            tag: master
            pullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi

  configMaps:
    config:
      enabled: true
      data:
        config.json: |
          {
            "directories": [
              {
                "name": "cl-full-checkpoint-sync",
                "displayName": "CL Fullnode + CL Checkpoint Sync",
                "url": "https://syncoor-data.ethpandaops.io/devnets/bal-devnet-0"
              },
              {
                "name": "cl-super-checkpoint-sync",
                "displayName": "CL Supernode + CL Checkpoint Sync",
                "url": "https://syncoor-data.ethpandaops.io/devnets/bal-devnet-0-clsupernode"
              },
              {
                "name": "cl-full-genesis-sync",
                "displayName": "CL Fullnode + CL Genesis Sync",
                "url": "https://syncoor-data.ethpandaops.io/devnets/bal-devnet-0-clcheckpointsyncdisabled"
              },
              {
                "name": "cl-super-genesis-sync",
                "displayName": "CL Supernode + CL Genesis Sync",
                "url": "https://syncoor-data.ethpandaops.io/devnets/bal-devnet-0-clsupernode-clcheckpointsyncdisabled"
              }
            ],
            "syncoorApiEndpoints": [
              {
                "name": "Syncoor",
                "url": "https://syncoor-api.bal-devnet-0.ethpandaops.io"
              }
            ]
          }

  ingress:
    main:
      className: ingress-nginx-public
      enabled: true
      hosts:
        - host: syncoor.bal-devnet-0.ethpandaops.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
