localhost

[all:vars]
ethereum_network_name=bal-devnet-7

[bootnode]
bootnode-1 ansible_host=178.105.49.28 ipv6=2a01:4f8:1c18:fe74::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True 

[lighthouse_besu]
lighthouse-besu-1 ansible_host=178.105.51.90 ipv6=2a01:4f8:1c18:3db0::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=200

[lighthouse_erigon]
lighthouse-erigon-1 ansible_host=178.105.171.26 ipv6=2a01:4f8:1c18:959e::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1200

[lighthouse_ethrex]
lighthouse-ethrex-1 ansible_host=178.105.160.43 ipv6=2a01:4f8:1c18:45d7::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=200 validator_end=400

[lighthouse_geth]
lighthouse-geth-1 ansible_host=178.104.17.134 ipv6=2a01:4f8:c2c:113f::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2400 validator_end=2600

[lighthouse_nethermind]
lighthouse-nethermind-1 ansible_host=178.105.166.136 ipv6=2a01:4f8:1c18:3744::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=400 validator_end=600

[lighthouse_nimbusel]
lighthouse-nimbusel-1 ansible_host=178.105.171.190 ipv6=2a01:4f8:1c18:78bc::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=600 validator_end=800

[lighthouse_reth]
lighthouse-reth-1 ansible_host=178.105.165.94 ipv6=2a01:4f8:1c18:7a18::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=800 validator_end=1000

[lodestar_besu]
lodestar-besu-1 ansible_host=178.105.86.19 ipv6=2a01:4f8:1c18:6a03::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1200 validator_end=1400

[lodestar_erigon]
lodestar-erigon-1 ansible_host=178.105.174.162 ipv6=2a01:4f8:1c18:474f::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2200 validator_end=2400

[lodestar_ethrex]
lodestar-ethrex-1 ansible_host=178.105.175.207 ipv6=2a01:4f8:1c18:2f06::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1400 validator_end=1600

[lodestar_geth]
lodestar-geth-1 ansible_host=178.104.143.237 ipv6=2a01:4f8:1c1b:cc7c::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2600 validator_end=2800

[lodestar_nethermind]
lodestar-nethermind-1 ansible_host=178.104.250.111 ipv6=2a01:4f8:1c18:3695::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1600 validator_end=1800

[lodestar_nimbusel]
lodestar-nimbusel-1 ansible_host=178.105.173.155 ipv6=2a01:4f8:1c18:42ca::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1800 validator_end=2000

[lodestar_reth]
lodestar-reth-1 ansible_host=178.105.167.107 ipv6=2a01:4f8:1c18:29bc::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=2200


# Consensus client groups

[lighthouse:children]
lighthouse_besu
lighthouse_erigon
lighthouse_ethrex
lighthouse_geth
lighthouse_nethermind
lighthouse_nimbusel
lighthouse_reth
[lodestar:children]
lodestar_besu
lodestar_erigon
lodestar_ethrex
lodestar_geth
lodestar_nethermind
lodestar_nimbusel
lodestar_reth
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
lighthouse_besu
lodestar_besu
[ethereumjs:children]
[geth:children]
lighthouse_geth
lodestar_geth
[nethermind:children]
lighthouse_nethermind
lodestar_nethermind
[erigon:children]
lighthouse_erigon
lodestar_erigon
[reth:children]
lighthouse_reth
lodestar_reth
[nimbusel:children]
lighthouse_nimbusel
lodestar_nimbusel
[ethrex:children]
lighthouse_ethrex
lodestar_ethrex

# Global groups

[consensus_node:children]
lighthouse
lodestar

[execution_node:children]
besu
erigon
ethrex
geth
nethermind
nimbusel
reth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
