# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: https://bn-bootnode-1.srv.bal-devnet-7.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lighthouse-besu-1.srv.bal-devnet-7.ethpandaops.io
  name: lighthouse-besu-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-erigon-1.srv.bal-devnet-7.ethpandaops.io
  name: lighthouse-erigon-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-ethrex-1.srv.bal-devnet-7.ethpandaops.io
  name: lighthouse-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-geth-1.srv.bal-devnet-7.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nethermind-1.srv.bal-devnet-7.ethpandaops.io
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nimbusel-1.srv.bal-devnet-7.ethpandaops.io
  name: lighthouse-nimbusel-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-reth-1.srv.bal-devnet-7.ethpandaops.io
  name: lighthouse-reth-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lodestar-besu-1.srv.bal-devnet-7.ethpandaops.io
  name: lodestar-besu-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-erigon-1.srv.bal-devnet-7.ethpandaops.io
  name: lodestar-erigon-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-ethrex-1.srv.bal-devnet-7.ethpandaops.io
  name: lodestar-ethrex-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-geth-1.srv.bal-devnet-7.ethpandaops.io
  name: lodestar-geth-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-nethermind-1.srv.bal-devnet-7.ethpandaops.io
  name: lodestar-nethermind-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-nimbusel-1.srv.bal-devnet-7.ethpandaops.io
  name: lodestar-nimbusel-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-reth-1.srv.bal-devnet-7.ethpandaops.io
  name: lodestar-reth-1
  authGroup: pandaops
  priority: -1

