xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "bal-devnet-3-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "bal-devnet-3"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://afa37cbdaa112f879574f6772d2383fc624733d9bb44f3181059a2fdf612c01af98ed3d77deec9b52da9b41ea67338d5321d80ab9cf04157bd2c6ab2c9153bbc@178.104.163.135:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
