localhost

[all:vars]
ethereum_network_name=bal-devnet-2

[bootnode]
hc-bootnode-1 ansible_host=116.203.97.137 ipv6=2a01:4f8:1c1c:51e3::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True 

[lighthouse_besu_noprefetch_super]
hc-lighthouse-besu-noprefetch-super-1 ansible_host=91.99.237.139 ipv6=2a01:4f8:1c19:e26e::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True 

[lighthouse_besu_optimized_super]
hc-lighthouse-besu-optimized-super-1 ansible_host=46.224.185.126 ipv6=2a01:4f8:1c1a:f643::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True 

[lighthouse_besu_sequential_super]
hc-lighthouse-besu-sequential-super-1 ansible_host=178.104.35.36 ipv6=2a01:4f8:1c19:cf7d::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True 

[lighthouse_besu_super]
hc-lighthouse-besu-super-1 ansible_host=188.245.250.30 ipv6=2a01:4f8:c0c:6cef::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=200 validator_end=400

[lighthouse_erigon_super]
hc-lighthouse-erigon-super-1 ansible_host=157.90.232.15 ipv6=2a01:4f8:1c19:8a51::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=2400 validator_end=2600

[lighthouse_ethrex_super]
hc-lighthouse-ethrex-super-1 ansible_host=46.224.231.54 ipv6=2a01:4f8:1c19:f6dc::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=2200

[lighthouse_geth_noprefetch_super]
hc-lighthouse-geth-noprefetch-super-1 ansible_host=178.104.45.168 ipv6=2a01:4f8:1c19:30d9::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True 

[lighthouse_geth_optimized_super]
hc-lighthouse-geth-optimized-super-1 ansible_host=178.104.38.68 ipv6=2a01:4f8:1c19:1655::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True 

[lighthouse_geth_sequential_super]
hc-lighthouse-geth-sequential-super-1 ansible_host=178.104.43.151 ipv6=2a01:4f8:1c19:8225::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True 

[lighthouse_geth_super]
hc-lighthouse-geth-super-1 ansible_host=91.99.49.166 ipv6=2a01:4f8:1c0c:566e::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=200

[lighthouse_nethermind_super]
hc-lighthouse-nethermind-super-1 ansible_host=88.198.203.108 ipv6=2a01:4f8:1c1a:2a62::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=400 validator_end=600

[lighthouse_nimbusel_super]
hc-lighthouse-nimbusel-super-1 ansible_host=91.99.236.162 ipv6=2a01:4f8:c0c:7e0a::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=800 validator_end=1000

[lighthouse_reth_super]
hc-lighthouse-reth-super-1 ansible_host=46.225.92.129 ipv6=2a01:4f8:1c19:2361::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=600 validator_end=800

[lodestar_besu_super]
hc-lodestar-besu-super-1 ansible_host=188.34.202.61 ipv6=2a01:4f8:c0c:85d7::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=1400 validator_end=1600

[lodestar_erigon_super]
hc-lodestar-erigon-super-1 ansible_host=188.245.244.41 ipv6=2a01:4f8:1c19:7c30::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=2600 validator_end=2800

[lodestar_ethrex_super]
hc-lodestar-ethrex-super-1 ansible_host=46.225.177.196 ipv6=2a01:4f8:1c19:41e::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=2200 validator_end=2400

[lodestar_geth_super]
hc-lodestar-geth-super-1 ansible_host=5.75.189.120 ipv6=2a01:4f8:1c1b:ab2b::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1200

[lodestar_nethermind_super]
hc-lodestar-nethermind-super-1 ansible_host=157.90.27.23 ipv6=2a01:4f8:1c1c:7eae::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=1200 validator_end=1400

[lodestar_nimbusel_super]
hc-lodestar-nimbusel-super-1 ansible_host=157.90.24.221 ipv6=2a01:4f8:1c1b:b8a2::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=1800 validator_end=2000

[lodestar_reth_super]
hc-lodestar-reth-super-1 ansible_host=78.47.36.173 ipv6=2a01:4f8:c0c:bd96::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True validator_start=1600 validator_end=1800


# Consensus client groups

[lighthouse:children]
lighthouse_besu_noprefetch_super
lighthouse_besu_optimized_super
lighthouse_besu_sequential_super
lighthouse_besu_super
lighthouse_erigon_super
lighthouse_ethrex_super
lighthouse_geth_noprefetch_super
lighthouse_geth_optimized_super
lighthouse_geth_sequential_super
lighthouse_geth_super
lighthouse_nethermind_super
lighthouse_nimbusel_super
lighthouse_reth_super
[lodestar:children]
lodestar_besu_super
lodestar_erigon_super
lodestar_ethrex_super
lodestar_geth_super
lodestar_nethermind_super
lodestar_nimbusel_super
lodestar_reth_super
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
lighthouse_besu_noprefetch_super
lighthouse_besu_optimized_super
lighthouse_besu_sequential_super
lighthouse_besu_super
lodestar_besu_super
[ethereumjs:children]
[geth:children]
lighthouse_geth_noprefetch_super
lighthouse_geth_optimized_super
lighthouse_geth_sequential_super
lighthouse_geth_super
lodestar_geth_super
[nethermind:children]
lighthouse_nethermind_super
lodestar_nethermind_super
[erigon:children]
lighthouse_erigon_super
lodestar_erigon_super
[reth:children]
lighthouse_reth_super
lodestar_reth_super
[nimbusel:children]
lighthouse_nimbusel_super
lodestar_nimbusel_super
[ethrex:children]
lighthouse_ethrex_super
lodestar_ethrex_super

# Global groups

[consensus_node:children]
lighthouse
lodestar

[execution_node:children]
besu
erigon
ethrex
geth
nethermind
nimbusel
reth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
