secret_fork_monitor_smtp:
    host: ENC[AES256_GCM,data:oPbxeBihD3sMi1o6i0Q=,iv:OeN15GJmmXw7mQmMpnuAEAzT8/cd+BNKq7+iIjxJMc0=,tag:V/sgmaiszNRgEFDPlvhMbA==,type:str]
    port: ENC[AES256_GCM,data:xmSQ,iv:OG/H/CJjstBryfQh3xxEhVeDwMGgXlZQyJThGzMtbPc=,tag:AUl9CpN+roa8CcxW6KC3wg==,type:int]
    user: ENC[AES256_GCM,data:hM+0vCPgxWlhi/wQQvQgjN0V60At,iv:t9Le0pHFIv3MW/d/kZF2HaXfCiq/ER+ETzZ/bG3sn2s=,tag:Q9fayv5GPAfEOiGRFNwmAQ==,type:str]
    password: ENC[AES256_GCM,data:1hfbTTdcpzvPpTykfo36Eg5FUQ==,iv:ngJqHHFdqnXK2RwG0RyfsATViUVKuPjVO2SJpPbzYFE=,tag:nO0NyUqXJ7KG/CqE5aDKBQ==,type:str]
    from: ENC[AES256_GCM,data:nL6ZuUWvo6iuFfh9ibGaBrIAPwU=,iv:BJFtMGl9MLp0/zdB5RFUuN5pN4SV1B8lLWXmOQ7J/wY=,tag:0J312CL6W7ZN0MWNU5KSUA==,type:str]
    to:
        - ENC[AES256_GCM,data:nTxSKdJGL0wCneX0PLObLT9SbA==,iv:24oxxoGAazUNi8EMHN0p0Y6htaEsVmGyxMly7omm96A=,tag:IxLmrBFZx4mtbuClH1SFdA==,type:str]
sops:
    lastmodified: "2026-02-07T20:46:08Z"
    mac: ENC[AES256_GCM,data:AzQpH4uY9mGazAzml4gG8/bnZ43hptXesoASLf/7kfkeqTOxzGlvY0Yw+lWPSyiFeAKx4YoitASoULFPtDUgoAFht1p4lM5PMbdCA8uQ2dMMUz1j3Fz+17373BB/CkzYOvYCsj4qiJS+1L9HwvJB+aCQwtk90fs8r2tg42vncXw=,iv:4ypIH8ltMXXKAbpzwx8H1IT37ZtiCTgbjAYLNHQLHII=,tag:1exNr2h/4XWawh6nZK0tmw==,type:str]
    pgp:
        - created_at: "2026-02-07T20:46:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAHAiEkhkdxArE3f+Db7RjzWJ4jK2y7ki99SMC3EyLXXgw
            w82YdyjT4/I1SdgPG6kvP0gGpYAsnS8GAW8E+Xk70cI1JdquVlHQLOLC7+C2/7ec
            1GgBCQIQ68+1t7dw0nsIMtQ/l2iZXevRh3IuuilE1H1T9eBkEshcRuyJ3PmFm8Ph
            B0ZCpHb3CFHpPROi8AkF1bhmg8qJzdVB2DRPJgC/ko5f7CqFJWd4B8jBzz4bWNoI
            ql0zus/3yArgPQ==
            =7qzL
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.10.2
