localhost

[all:vars]
ethereum_network_name=bal-devnet-6

[bootnode]
bootnode-1 ansible_host=178.104.149.197 ipv6=2a01:4f8:1c1a:ff53::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True 

[lighthouse_besu]
lighthouse-besu-1 ansible_host=178.105.58.6 ipv6=2a01:4f8:1c19:98aa::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=200 validator_end=400

[lighthouse_ethrex]
lighthouse-ethrex-1 ansible_host=178.105.41.0 ipv6=2a01:4f8:1c1a:a7fa::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=400 validator_end=600

[lighthouse_geth]
lighthouse-geth-1 ansible_host=178.104.234.238 ipv6=2a01:4f8:1c1a:68d3::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=200

[lodestar_besu]
lodestar-besu-1 ansible_host=178.105.59.223 ipv6=2a01:4f8:1c18:1010::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=800 validator_end=1000

[lodestar_ethrex]
lodestar-ethrex-1 ansible_host=188.245.64.72 ipv6=2a01:4f8:1c1a:a007::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1200

[lodestar_geth]
lodestar-geth-1 ansible_host=168.119.168.50 ipv6=2a01:4f8:1c18:1b8c::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=600 validator_end=800


# Consensus client groups

[lighthouse:children]
lighthouse_besu
lighthouse_ethrex
lighthouse_geth
[lodestar:children]
lodestar_besu
lodestar_ethrex
lodestar_geth
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
lighthouse_besu
lodestar_besu
[ethereumjs:children]
[geth:children]
lighthouse_geth
lodestar_geth
[nethermind:children]
[erigon:children]
[reth:children]
[nimbusel:children]
[ethrex:children]
lighthouse_ethrex
lodestar_ethrex

# Global groups

[consensus_node:children]
lighthouse
lodestar

[execution_node:children]
besu
ethrex
geth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
