localhost

[all:vars]
ethereum_network_name=bal-devnet-6

[bootnode]

[lighthouse_besu]

[lighthouse_erigon]

[lighthouse_ethrex]

[lighthouse_geth]

[lighthouse_nethermind]

[lighthouse_reth]

[lodestar_besu]

[lodestar_erigon]

[lodestar_ethrex]

[lodestar_geth]

[lodestar_nethermind]

[lodestar_reth]


# Consensus client groups

[lighthouse:children]
lighthouse_besu
lighthouse_erigon
lighthouse_ethrex
lighthouse_geth
lighthouse_nethermind
lighthouse_reth
[lodestar:children]
lodestar_besu
lodestar_erigon
lodestar_ethrex
lodestar_geth
lodestar_nethermind
lodestar_reth
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
lighthouse_besu
lodestar_besu
[ethereumjs:children]
[geth:children]
lighthouse_geth
lodestar_geth
[nethermind:children]
lighthouse_nethermind
lodestar_nethermind
[erigon:children]
lighthouse_erigon
lodestar_erigon
[reth:children]
lighthouse_reth
lodestar_reth
[ethrex:children]
lighthouse_ethrex
lodestar_ethrex

# Global groups

[consensus_node:children]
lighthouse
lodestar

[execution_node:children]
besu
erigon
ethrex
geth
nethermind
reth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
