# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: https://bn-bootnode-1.srv.bal-devnet-3.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lighthouse-besu-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lighthouse-besu-super-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-erigon-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lighthouse-erigon-super-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-ethrex-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lighthouse-ethrex-super-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-geth-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lighthouse-geth-super-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nethermind-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lighthouse-nethermind-super-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nimbusel-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lighthouse-nimbusel-super-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-reth-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lighthouse-reth-super-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lodestar-besu-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lodestar-besu-super-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-erigon-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lodestar-erigon-super-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-ethrex-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lodestar-ethrex-super-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-geth-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lodestar-geth-super-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-nethermind-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lodestar-nethermind-super-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-nimbusel-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lodestar-nimbusel-super-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lodestar-reth-super-1.srv.bal-devnet-3.ethpandaops.io
  name: lodestar-reth-super-1
  authGroup: pandaops
  priority: -1

