localhost

[all:vars]
ethereum_network_name=bal-devnet-3

[bootnode]
bootnode-1 ansible_host=178.104.163.135 ipv6=2a01:4f8:1c18:c667::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True 

[lighthouse_besu_super]
lighthouse-besu-super-1 ansible_host=178.104.164.200 ipv6=2a01:4f8:1c18:7615::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=200 validator_end=400

[lighthouse_erigon_super]
lighthouse-erigon-super-1 ansible_host=178.104.171.252 ipv6=2a01:4f8:1c18:da2d::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1200 validator_end=1400

[lighthouse_ethrex_super]
lighthouse-ethrex-super-1 ansible_host=178.104.162.229 ipv6=2a01:4f8:1c18:ae76::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1200

[lighthouse_geth_super]
lighthouse-geth-super-1 ansible_host=178.104.170.143 ipv6=2a01:4f8:1c18:de50::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=200

[lighthouse_nethermind_super]
lighthouse-nethermind-super-1 ansible_host=178.104.173.113 ipv6=2a01:4f8:1c18:b72d::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=400 validator_end=600

[lighthouse_nimbusel_super]
lighthouse-nimbusel-super-1 ansible_host=178.104.166.39 ipv6=2a01:4f8:1c18:a37::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=800 validator_end=1000

[lighthouse_reth_super]
lighthouse-reth-super-1 ansible_host=178.104.164.69 ipv6=2a01:4f8:1c18:5546::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=600 validator_end=800

[lodestar_besu_super]
lodestar-besu-super-1 ansible_host=178.104.171.24 ipv6=2a01:4f8:1c18:b610::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1600 validator_end=1800

[lodestar_erigon_super]
lodestar-erigon-super-1 ansible_host=178.104.161.162 ipv6=2a01:4f8:1c18:30c4::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2600 validator_end=2800

[lodestar_ethrex_super]
lodestar-ethrex-super-1 ansible_host=178.104.161.203 ipv6=2a01:4f8:1c18:8e68::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2400 validator_end=2600

[lodestar_geth_super]
lodestar-geth-super-1 ansible_host=178.104.173.228 ipv6=2a01:4f8:1c18:b05f::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1400 validator_end=1600

[lodestar_nethermind_super]
lodestar-nethermind-super-1 ansible_host=178.104.167.130 ipv6=2a01:4f8:1c18:b903::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1800 validator_end=2000

[lodestar_nimbusel_super]
lodestar-nimbusel-super-1 ansible_host=178.104.173.253 ipv6=2a01:4f8:1c18:ea5::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2200 validator_end=2400

[lodestar_reth_super]
lodestar-reth-super-1 ansible_host=178.104.175.230 ipv6=2a01:4f8:1c18:5237::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=2200


# Consensus client groups

[lighthouse:children]
lighthouse_besu_super
lighthouse_erigon_super
lighthouse_ethrex_super
lighthouse_geth_super
lighthouse_nethermind_super
lighthouse_nimbusel_super
lighthouse_reth_super
[lodestar:children]
lodestar_besu_super
lodestar_erigon_super
lodestar_ethrex_super
lodestar_geth_super
lodestar_nethermind_super
lodestar_nimbusel_super
lodestar_reth_super
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
lighthouse_besu_super
lodestar_besu_super
[ethereumjs:children]
[geth:children]
lighthouse_geth_super
lodestar_geth_super
[nethermind:children]
lighthouse_nethermind_super
lodestar_nethermind_super
[erigon:children]
lighthouse_erigon_super
lodestar_erigon_super
[reth:children]
lighthouse_reth_super
lodestar_reth_super
[nimbusel:children]
lighthouse_nimbusel_super
lodestar_nimbusel_super
[ethrex:children]
lighthouse_ethrex_super
lodestar_ethrex_super

# Global groups

[consensus_node:children]
lighthouse
lodestar

[execution_node:children]
besu
erigon
ethrex
geth
nethermind
nimbusel
reth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
